version: '3.2'

services:
  jenkins:
    image: eid-jenkins02.dmz.local:8081/eid-jenkins:${VERSION}
    ports:
      - "80:8080"
    environment:
      DOCKER_HOST: tcp://eid-jenkins02.dmz.local:2376
      REPOSITORIES: >
        eid;git@git.difi.local:eid;ssh.git.difi.local;
        jenkins-docker;git@github.com:difi/jenkins-docker;ssh.git.difi.local;
        kontaktregister-statistikk;https://github.com/difi/kontaktregister-statistikk;;
        idporten-oidc-client;git@github.com:difi/idporten-klient-oidc.git;ssh.git.difi.local;
        krr-oauth2-server;git@git.difi.local:krr-oauth2-server;ssh.git.difi.local;
        poc-statistics;https://github.com/difi/poc-statistics;;
        eid-oidc-provider;git@git.difi.local:eid-oidc-provider;ssh.git.difi.local;
        minid-on-the-fly;git@git.difi.local:minid-on-the-fly;ssh.git.difi.local;
        eid-resilience;git@git.difi.local:eid-common-resilience.git;ssh.git.difi.local;
        eid-common;git@git.difi.local:eid-common.git;ssh.git.difi.local;
        krr;git@git.difi.local:krr.git;ssh.git.difi.local;
        idporten;git@git.difi.local:idporten.git;ssh.git.difi.local;
        idporten-admin;git@git.difi.local:idporten-admin.git;ssh.git.difi.local;
        idporten-authlevel;git@git.difi.local:idporten-authlevel.git;ssh.git.difi.local;
        idporten-app-dpi-reklame;git@git.difi.local:idporten-app-dpi-reklame.git;ssh.git.difi.local;
        idporten-minid-updater;git@git.difi.local:idporten-minid-updater.git;ssh.git.difi.local;
        idporten-pinkoder;git@git.difi.local:idporten-pinkoder.git;ssh.git.difi.local;
        dine-kontaktopplysninger;git@git.difi.local:dine-kontaktopplysninger.git;ssh.git.difi.local;
        dsf-gateway;git@git.difi.local:dsf-gateway.git;ssh.git.difi.local;
        eid-level1-poc;git@git.difi.local:eid-level1-poc.git;ssh.git.difi.local;
        eid-system-tests;git@git.difi.local:eid-system-tests.git;ssh.git.difi.local;
        eid-pipeline-branch;git@git.difi.local:eid-pipeline-branch.git;ssh.git.difi.local;
        eid-pipeline;git@git.difi.local:eid-pipeline.git;ssh.git.difi.local;
        eid-log-writer;git@git.difi.local:eid-log-writer.git;ssh.git.difi.local;
        eidas;git@git.difi.local:eidas.git;ssh.git.difi.local;
      KNOWN_HOSTS: |
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
        git.difi.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG4VYlrX7IlRq+O1lokYTp1oYe7vsIPAmm9uhDec2TVvCkPnSeNhJq9iCyRYCaaCxZLRfUjQdCNc6NvNyXdZb6k=
        eid-gitlab.dmz.local ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEApaqpEGnJ/z4Ur+bgHhnpYCBCdyPuDMVxUplgVPaUTjCLEiEioU+LgZsr04pX6s9sqHbH+0+ggAizxpXQZJ4AOgyeSCwtZNpqX3jXdXMCXqjQgDY/Pxu1vi91PucNK8B4lwkrhed9Ze8iCzdKY5w1NZDpB6Auc+UL2I0HJNDIlrxenYXdqtK6udLyEv1eViGCOIPY1YJ1SjVxMWv2G4itdJDQrOqe6U3p5Ph3P810rtIh/q4Z1PbdS98Jvh3VewdMpQjqPSTskn+EsnlEGJf8vvJmsVsRol1X5bmU/mxIXsaySzPmKdH34hQFzdejdjp83FYRffV0OYhL8Ur9ZU+Apw==
        eid-jenkins02.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBC1UgDT1mm3EJ2w90x2zeEVzxdFPxcqkp+a0N6+0WLgNgTLVFRt2/hSM48VfCaFQaOzVw8PfxVSIHtuunFry1qo=
        eid-test-oidc-provider.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMzEIRiGtC0hPPq9mDXqw+TCye5gzFGI8mouaeIMRaRwHhI5rh1PZ39SbzzOgpAT2hW8YRkwBYMN5qCZnfJ0KCI=
        eid-test-oidc-klient.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBhqhkaSU8DLfbTzM1nVZFIciooTYIluNkRdTznEqZGUP3I6YYW9OTQDP/8cgWhv22l3lVmFLSrsxgf0IsBXI1I=
        eid-oidc-provider.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLtZOtk+k07ET+seli2lXbKYSaCae0wnP/OyA+o84epOGuGU+zT69Jqo0Bugll/It1xJ8C+IJthd9XfnlAx4tOA=
      uid: '${uid}'
      gid: '${gid}'
    deploy:
      placement:
        constraints:
          - node.role == manager
    secrets:
      - source: ssh.git.difi.local
        target: ssh.git.difi.local
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: ssh.github.com
        target: ssh.github.com
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: artifactory-cleaner
        target: artifactory-cleaner
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: crucible_username
        target: crucible_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: crucible_password
        target: crucible_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: nexus_username
        target: nexus_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: nexus_password
        target: nexus_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
    volumes:
      - type: bind
        source: ${SSH_AUTH_SOCK}
        target: /ssh_auth_sock
      - type: bind
        source: ${HOME}/data
        target: /var/jenkins_home
      - type: bind
        source: ${HOME}/.docker
        target: /var/jenkins_home/.docker
      - type: bind
        source: ${HOME}/.m2
        target: /var/jenkins_home/.m2
      - type: bind
        source: ${HOME}/.aws
        target: /var/jenkins_home/.aws
    networks:
      - pipeline
  nexus:
    image: sonatype/nexus3:3.3.2
    ports:
      - "8080:8081"
      - "8081:8082"
    networks:
      - pipeline
    deploy:
      placement:
        constraints:
          - node.role == manager
  selenium_host:
    image: selenium/standalone-firefox:2.53.0
    ports:
      - "4444:4444"
    networks:
      - pipeline

volumes:
  nexus-data:
    external: true

networks:
  pipeline:
    driver: overlay
    attachable: true

secrets:
  ssh.git.difi.local:
    external: true
  ssh.github.com:
    external: true
  artifactory-cleaner:
    external: true
  crucible_username:
    external: true
  crucible_password:
    external: true
  nexus_username:
    external: true
  nexus_password:
    external: true
