version: '3.4'

services:
  jenkins-slave-1:
    image: eid-jenkins02.dmz.local:8081/jenkins-slave:${VERSION}
    configs:
      - source: pipeline-config
        target: /config.yaml
    environment:
      SERVICE: jenkins-slave-1
    deploy:
      placement:
        constraints:
          - node.labels.jenkins-slave == true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-workspaces:/workspaces
      - jenkins-ssh-settings:/etc/ssh
    networks:
      - pipeline
  jenkins-slave-2:
    image: eid-jenkins02.dmz.local:8081/jenkins-slave:${VERSION}
    configs:
      - source: pipeline-config
        target: /config.yaml
    environment:
      SERVICE: jenkins-slave-2
    deploy:
      placement:
        constraints:
          - node.labels.jenkins-slave == true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-workspaces:/workspaces
      - jenkins-ssh-settings:/etc/ssh
    networks:
      - pipeline
  jenkins:
    image: eid-jenkins02.dmz.local:8081/jenkins:${VERSION}
    ports:
      - "80:8080"
    configs:
      - source: pipeline-jobs
        target: /jobs.yaml
      - source: pipeline-config
        target: /config.yaml
    environment:
      JENKINS_SLAVES: jenkins-slave-1,jenkins-slave-2
      DOCKER_HOST: tcp://eid-jenkins02.dmz.local:2376
      uid: '${uid}'
      gid: '${gid}'
    deploy:
      placement:
        constraints:
          - node.labels.jenkins-master == true
    secrets:
      - source: docker_registry_StagingLocal_username
        target: docker_registry_StagingLocal_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker_registry_StagingLocal_password
        target: docker_registry_StagingLocal_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker_registry_StagingPublic_username
        target: docker_registry_StagingPublic_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker_registry_StagingPublic_password
        target: docker_registry_StagingPublic_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker_registry_ProductionLocal_username
        target: docker_registry_ProductionLocal_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker_registry_ProductionLocal_password
        target: docker_registry_ProductionLocal_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker_registry_ProductionPublic_username
        target: docker_registry_ProductionPublic_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker_registry_ProductionPublic_password
        target: docker_registry_ProductionPublic_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: ssh.git.difi.local
        target: ssh.git.difi.local
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: ssh.github.com
        target: ssh.github.com
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: artifactory_username
        target: artifactory_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: artifactory_password
        target: artifactory_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: artifactory-cleaner
        target: artifactory-cleaner
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: crucible_username
        target: crucible_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: crucible_password
        target: crucible_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: nexus_username
        target: nexus_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: nexus_password
        target: nexus_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: jira_username
        target: jira_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: jira_password
        target: jira_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: aws_username
        target: aws_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: aws_password
        target: aws_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: dockerHub_username
        target: dockerHub_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: dockerHub_password
        target: dockerHub_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-ca.eid-jenkins02.dmz.local
        target: docker-ca.agent
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-cert.eid-jenkins02.dmz.local
        target: docker-cert.agent
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-key.eid-jenkins02.dmz.local
        target: docker-key.agent
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-ca.eid-jenkins03.dmz.local
        target: docker-ca.build
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-cert.eid-jenkins03.dmz.local
        target: docker-cert.build
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-key.eid-jenkins03.dmz.local
        target: docker-key.build
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-workspaces:/workspaces
      - jenkins-builds:/builds
      - jenkins-ssh-settings:/etc/ssh
    networks:
      pipeline:
  nexus:
    image: eid-jenkins02.dmz.local:8081/nexus:2017-09-29
    ports:
      - "8080:8081"
      - "8081:8082"
      - "8082:8083"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - pipeline
    deploy:
      placement:
        constraints:
          - node.labels.nexus == true

volumes:
  nexus-data:
    external: true
  jenkins-data:
    external: true
  jenkins-workspaces:
    external: true
  jenkins-builds:
    external: true
  jenkins-ssh-settings:
    external: true

configs:
  pipeline-jobs:
    external: true
  pipeline-config:
    external: true

networks:
  pipeline:
    driver: overlay
    attachable: true

secrets:
  docker_registry_StagingLocal_username:
    external: true
  docker_registry_StagingLocal_password:
    external: true
  docker_registry_StagingPublic_username:
    external: true
  docker_registry_StagingPublic_password:
    external: true
  docker_registry_ProductionLocal_username:
    external: true
  docker_registry_ProductionLocal_password:
    external: true
  docker_registry_ProductionPublic_username:
    external: true
  docker_registry_ProductionPublic_password:
    external: true
  ssh.git.difi.local:
    external: true
  ssh.github.com:
    external: true
  artifactory-cleaner:
    external: true
  artifactory_username:
    external: true
  artifactory_password:
    external: true
  crucible_username:
    external: true
  crucible_password:
    external: true
  nexus_username:
    external: true
  nexus_password:
    external: true
  jira_username:
    external: true
  jira_password:
    external: true
  aws_username:
    external: true
  aws_password:
    external: true
  dockerHub_username:
    external: true
  dockerHub_password:
    external: true
  docker-ca.eid-jenkins02.dmz.local:
    external: true
  docker-cert.eid-jenkins02.dmz.local:
    external: true
  docker-key.eid-jenkins02.dmz.local:
    external: true
  docker-ca.eid-jenkins03.dmz.local:
    external: true
  docker-cert.eid-jenkins03.dmz.local:
    external: true
  docker-key.eid-jenkins03.dmz.local:
    external: true
