version: '3.4'

services:
  jenkins:
    image: eid-jenkins02.dmz.local:8081/jenkins:${VERSION}
    ports:
      - "80:8080"
    configs:
      - source: pipeline-jobs
        target: /jobs.yaml
    environment:
      JIRA_URL: http://jira.difi.local
      ISSUE_STATUS_OPEN: 1
      ISSUE_STATUS_IN_PROGRESS: 3
      ISSUE_STATUS_CODE_APPROVED: 10005
      ISSUE_STATUS_CODE_REVIEW: 10012
      ISSUE_STATUS_MANUAL_VERIFICATION: 10009
      ISSUE_STATUS_MANUAL_VERIFICATION_OK: 10010
      ISSUE_TRANSITION_START: 371
      ISSUE_TRANSITION_READY_FOR_CODE_REVIEW: 391
      ISSUE_TRANSITION_RESUME_WORK: 301
      DOCKER_HOST: tcp://eid-jenkins02.dmz.local:2376
      KNOWN_HOSTS: |
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
        git.difi.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG4VYlrX7IlRq+O1lokYTp1oYe7vsIPAmm9uhDec2TVvCkPnSeNhJq9iCyRYCaaCxZLRfUjQdCNc6NvNyXdZb6k=
        eid-gitlab.dmz.local ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEApaqpEGnJ/z4Ur+bgHhnpYCBCdyPuDMVxUplgVPaUTjCLEiEioU+LgZsr04pX6s9sqHbH+0+ggAizxpXQZJ4AOgyeSCwtZNpqX3jXdXMCXqjQgDY/Pxu1vi91PucNK8B4lwkrhed9Ze8iCzdKY5w1NZDpB6Auc+UL2I0HJNDIlrxenYXdqtK6udLyEv1eViGCOIPY1YJ1SjVxMWv2G4itdJDQrOqe6U3p5Ph3P810rtIh/q4Z1PbdS98Jvh3VewdMpQjqPSTskn+EsnlEGJf8vvJmsVsRol1X5bmU/mxIXsaySzPmKdH34hQFzdejdjp83FYRffV0OYhL8Ur9ZU+Apw==
        eid-jenkins02.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBC1UgDT1mm3EJ2w90x2zeEVzxdFPxcqkp+a0N6+0WLgNgTLVFRt2/hSM48VfCaFQaOzVw8PfxVSIHtuunFry1qo=
        eid-jenkins03.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLLtI8VjTpcgoKoer2t8K3eFvT6/23ajAsT6U4tk5TaqDMteJzrE/p8v+XzcrMrWPaqdxZV4h+uLYv5VtyDeZRU=
        eid-test-oidc-provider.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMzEIRiGtC0hPPq9mDXqw+TCye5gzFGI8mouaeIMRaRwHhI5rh1PZ39SbzzOgpAT2hW8YRkwBYMN5qCZnfJ0KCI=
        eid-test-oidc-klient.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBhqhkaSU8DLfbTzM1nVZFIciooTYIluNkRdTznEqZGUP3I6YYW9OTQDP/8cgWhv22l3lVmFLSrsxgf0IsBXI1I=
        eid-oidc-provider.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLtZOtk+k07ET+seli2lXbKYSaCae0wnP/OyA+o84epOGuGU+zT69Jqo0Bugll/It1xJ8C+IJthd9XfnlAx4tOA=
        eid-test01.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKjTYi07cANNMTe0SwFEk6bq5VIp1inb2k1bUnL3bodhwUny9yG1amchjgvgmTol84niKETBOYVnGBqDh9UUNIs=
        eid-test-docker01.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIYFaQAAGYZMGs2nuTF1kSvU43HQk759zCbU4SMKr1je08/6AfgRmQ8MwVGb+glKplAOP4mD1La92Ltj2DjamNo=
        eid-prod-docker01.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCQ1MR4RdFoP7lNSI6sJW4b1p6+6GrCl5mUTQ4Fyqhsj7e8IFKyZS5/cUqhgu+z69y0d+5ZdZoy9gcnx1iDZCW0=      uid: '${uid}'
      uid: '${uid}'
      gid: '${gid}'
    deploy:
      placement:
        constraints:
          - node.labels.jenkins-master == true
    secrets:
      - source: ssh.git.difi.local
        target: ssh.git.difi.local
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: ssh.github.com
        target: ssh.github.com
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: artifactory_username
        target: artifactory_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: artifactory_password
        target: artifactory_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: artifactory-cleaner
        target: artifactory-cleaner
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: crucible_username
        target: crucible_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: crucible_password
        target: crucible_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: nexus_username
        target: nexus_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: nexus_password
        target: nexus_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: jira_username
        target: jira_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: jira_password
        target: jira_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: aws_username
        target: aws_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: aws_password
        target: aws_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: dockerHub_username
        target: dockerHub_username
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: dockerHub_password
        target: dockerHub_password
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-ca.eid-jenkins02.dmz.local
        target: docker-ca.agent
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-cert.eid-jenkins02.dmz.local
        target: docker-cert.agent
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-key.eid-jenkins02.dmz.local
        target: docker-key.agent
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-ca.eid-jenkins03.dmz.local
        target: docker-ca.build
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-cert.eid-jenkins03.dmz.local
        target: docker-cert.build
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
      - source: docker-key.eid-jenkins03.dmz.local
        target: docker-key.build
        mode: 0400
        uid: '${uid}'
        gid: '${gid}'
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - pipeline
  nexus:
    image: eid-jenkins02.dmz.local:8081/nexus:2017-09-29
    ports:
      - "8080:8081"
      - "8081:8082"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - pipeline
    deploy:
      placement:
        constraints:
          - node.labels.nexus == true
  selenium_host:
    image: selenium/standalone-firefox-debug:3.5.0
    ports:
      - "4444:4444"
    networks:
      - pipeline
    deploy:
      placement:
        constraints:
          - node.labels.jenkins-master != true

volumes:
  nexus-data:
    external: true
  jenkins-data:
    external: true

configs:
  pipeline-jobs:
    external: true

networks:
  pipeline:
    driver: overlay
    attachable: true

secrets:
  ssh.git.difi.local:
    external: true
  ssh.github.com:
    external: true
  artifactory-cleaner:
    external: true
  artifactory_username:
    external: true
  artifactory_password:
    external: true
  crucible_username:
    external: true
  crucible_password:
    external: true
  nexus_username:
    external: true
  nexus_password:
    external: true
  jira_username:
    external: true
  jira_password:
    external: true
  aws_username:
    external: true
  aws_password:
    external: true
  dockerHub_username:
    external: true
  dockerHub_password:
    external: true
  docker-ca.eid-jenkins02.dmz.local:
    external: true
  docker-cert.eid-jenkins02.dmz.local:
    external: true
  docker-key.eid-jenkins02.dmz.local:
    external: true
  docker-ca.eid-jenkins03.dmz.local:
    external: true
  docker-cert.eid-jenkins03.dmz.local:
    external: true
  docker-key.eid-jenkins03.dmz.local:
    external: true
